[package]
name = "SLMagic"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = {version="1.0", features= ["derive"] }
tokio = { version = "1", features = ["full"] }
tokio-test = "0.4.4"
serde_json = "1.0.120"